apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "sonarsource.parflesh.github.io/v1alpha1",
          "kind": "SonarQube",
          "metadata": {
            "name": "example-sonarqube"
          },
          "spec": {}
        },
        {
          "apiVersion": "sonarsource.parflesh.github.io/v1alpha1",
          "kind": "SonarQubeServer",
          "metadata": {
            "name": "example-sonarqubeserver"
          },
          "spec": {}
        }
      ]
    capabilities: Basic Install
  name: sonarqube-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: SonarQube is the Schema for the sonarqubes API
      kind: SonarQube
      name: sonarqubes.sonarsource.parflesh.github.io
      resources:
      - kind: Secret
        name: ""
        version: v1
      - kind: Service
        name: ""
        version: v1
      - kind: StatefulSet
        name: ""
        version: v1
      specDescriptors:
      - description: Run SonarQube as a cluster
        displayName: Clustered
        path: clustered
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
        - urn:alm:descriptor:com.tectonic.ui:fieldGroup:instance
      - description: Image of SonarQube to deploy
        displayName: Image
        path: image
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Node Affinity
        displayName: Node Affinity
        path: node.nodeAffinity
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
        - urn:alm:descriptor:com.tectonic.ui:fieldGroup:node.application.advanced
        - urn:alm:descriptor:com.tectonic.ui:nodeAffinity
      - description: Node selector
        displayName: Node Selector
        path: node.nodeSelector
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
        - urn:alm:descriptor:com.tectonic.ui:fieldGroup:node.application.advanced
        - urn:alm:descriptor:com.tectonic.ui:selector:Node
      - description: Pod Affinity
        displayName: Pod Affinity
        path: node.podAffinity
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
        - urn:alm:descriptor:com.tectonic.ui:fieldGroup:node.application.advanced
        - urn:alm:descriptor:com.tectonic.ui:podAffinity
      - description: Pod AntiAffinity
        displayName: Pod AntiAffinity
        path: node.podAntiAffinity
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
        - urn:alm:descriptor:com.tectonic.ui:fieldGroup:node.application.advanced
        - urn:alm:descriptor:com.tectonic.ui:podAntiAffinity
      - description: Priority Class Name
        displayName: Priority Class
        path: node.priorityClass
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
        - urn:alm:descriptor:com.tectonic.ui:fieldGroup:node.application.advanced
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Storage Class Name
        displayName: Storage Class Name
        path: node.storage.class
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:fieldGroup:node.application.storage
        - urn:alm:descriptor:io.kubernetes:StorageClass
      - description: Data Volume Size
        displayName: Data Volume Size
        path: node.storage.data
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:fieldGroup:node.application.storage
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Extensions Volume Size
        displayName: Extensions Volume Size
        path: node.storage.extensions
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:fieldGroup:node.application.storage
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Node Affinity
        displayName: Node Affinity
        path: nodeSearch.nodeAffinity
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
        - urn:alm:descriptor:com.tectonic.ui:fieldGroup:node.search.advanced
        - urn:alm:descriptor:com.tectonic.ui:nodeAffinity
      - description: Node selector
        displayName: Node Selector
        path: nodeSearch.nodeSelector
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
        - urn:alm:descriptor:com.tectonic.ui:fieldGroup:node.search.advanced
        - urn:alm:descriptor:com.tectonic.ui:selector:Node
      - description: Pod Affinity
        displayName: Pod Affinity
        path: nodeSearch.podAffinity
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
        - urn:alm:descriptor:com.tectonic.ui:fieldGroup:node.search.advanced
        - urn:alm:descriptor:com.tectonic.ui:podAffinity
      - description: Pod AntiAffinity
        displayName: Pod AntiAffinity
        path: nodeSearch.podAntiAffinity
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
        - urn:alm:descriptor:com.tectonic.ui:fieldGroup:node.search.advanced
        - urn:alm:descriptor:com.tectonic.ui:podAntiAffinity
      - description: Priority Class Name
        displayName: Priority Class
        path: nodeSearch.priorityClass
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
        - urn:alm:descriptor:com.tectonic.ui:fieldGroup:node.search.advanced
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Storage Class Name
        displayName: Storage Class Name
        path: nodeSearch.storage.class
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:fieldGroup:node.search.storage
        - urn:alm:descriptor:io.kubernetes:StorageClass
      - description: Data Volume Size
        displayName: Data Volume Size
        path: nodeSearch.storage.data
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:fieldGroup:node.search.storage
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Extensions Volume Size
        displayName: Extensions Volume Size
        path: nodeSearch.storage.extensions
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:fieldGroup:node.search.storage
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Secret with sonar configuration files (sonar.properties). Don't
          add cluster properties to configuration files as this could cause unexpected
          results
        displayName: Secret
        path: secret
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:fieldGroup:instance
        - urn:alm:descriptor:io.kubernetes:Secret
      - description: Size of SonarQube Cluster (0 will shutdown application and search
          nodes)
        displayName: Size
        path: size
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:number
        - urn:alm:descriptor:com.tectonic.ui:podCount
      - description: Version of SonarQube image to deploy
        displayName: Version
        path: version
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:fieldGroup:instance
        - urn:alm:descriptor:com.tectonic.ui:text
      statusDescriptors:
      - description: Status of pods
        displayName: Pod Statuses
        path: pods
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:podStatuses
      - description: Status of search pods
        displayName: Search Pod Statuses
        path: searchPods
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:podStatuses
      - description: Kubernetes service that can be used to expose SonarQube
        displayName: Service
        path: service
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes:Service
      version: v1alpha1
    - description: SonarQubeServer is the Schema for the sonarqubeservers API
      kind: SonarQubeServer
      name: sonarqubeservers.sonarsource.parflesh.github.io
      specDescriptors:
      - description: Enable clustering
        displayName: Enabled
        path: cluster.enabled
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - description: SonarQube application hosts list
        displayName: Hosts
        path: cluster.hosts
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
        - urn:alm:descriptor:com.tectonic.ui:arrayFieldGroup:hosts
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - description: SonarQube search hosts list
        displayName: Search Hosts
        path: cluster.searchHosts
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
        - urn:alm:descriptor:com.tectonic.ui:arrayFieldGroup:searchHosts
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - description: Sonar Node Type application or search when clustering is enabled
          otherwise aio (all-in-one)
        displayName: Secret
        path: cluster.type
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:select:aio
        - urn:alm:descriptor:com.tectonic.ui:select:application
        - urn:alm:descriptor:com.tectonic.ui:select:search
      - description: Node Affinity
        displayName: Node Affinity
        path: deployment.nodeAffinity
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
        - urn:alm:descriptor:com.tectonic.ui:nodeAffinity
      - description: Node selector
        displayName: Node Selector
        path: deployment.nodeSelector
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
        - urn:alm:descriptor:com.tectonic.ui:selector:Node
      - description: Pod Affinity
        displayName: Pod Affinity
        path: deployment.podAffinity
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
        - urn:alm:descriptor:com.tectonic.ui:podAffinity
      - description: Pod AntiAffinity
        displayName: Pod AntiAffinity
        path: deployment.podAntiAffinity
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
        - urn:alm:descriptor:com.tectonic.ui:podAntiAffinity
      - description: Priority Class Name
        displayName: Priority Class
        path: deployment.priorityClass
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Image of SonarQube to deploy
        displayName: Image
        path: image
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Secret with sonar configuration files (sonar.properties). Don't
          add cluster properties to configuration files as this could cause unexpected
          results
        displayName: Secret
        path: secret
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes:Secret
      - description: 0 and 1 are the only valid options.  Used to start and stop server.
        displayName: Size
        path: size
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:podCount
      - description: Storage Class Name
        displayName: Data Storage Class Name
        path: storage.dataClass
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:fieldGroup:storage
        - urn:alm:descriptor:io.kubernetes:StorageClass
      - description: Data Volume Size
        displayName: Data Volume Size
        path: storage.dataSize
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:fieldGroup:storage
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Storage Class Name
        displayName: Extensions Storage Class Name
        path: storage.extensionsClass
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:fieldGroup:storage
        - urn:alm:descriptor:io.kubernetes:StorageClass
      - description: Extensions Volume Size
        displayName: Extensions Volume Size
        path: storage.extensionsSize
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:fieldGroup:storage
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Version of SonarQube image to deploy
        displayName: Version
        path: version
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      statusDescriptors:
      - description: Status of pods
        displayName: Pod Statuses
        path: deployment
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:podStatuses
      - description: Kubernetes service that can be used to expose SonarQubeServer
        displayName: Service
        path: service
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes:Service
      version: v1alpha1
  description: |-
    WIP
    Creates SonarQube servers and clusters
  displayName: Sonarqube Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments:
      - name: sonarqube-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: sonarqube-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: sonarqube-operator
            spec:
              containers:
              - command:
                - sonarqube-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: sonarqube-operator
                image: quay.io/parflesh/sonarqube-operator:0.0.1
                imagePullPolicy: Always
                name: sonarqube-operator
                resources: {}
              serviceAccountName: sonarqube-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - sonarqube-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - sonarsource.parflesh.github.io
          resources:
          - '*'
          - sonarqubeservers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: sonarqube-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - SonarQube
  maintainers:
  - {}
  maturity: alpha
  provider:
    name: ParFlesh
  version: 0.0.1
